# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: jmaldonadoug
# "service" is the name of this project. This will also be added to your AWS resource names.
service: cloud-computing-proyecto-final-backend

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
